export enum ListRoles {
	ROLE_TYPE_ADMIN = 'admin',
	ROLE_TYPE_SAAS = 'saas',
	ROLE_TYPE_USER = 'user',
	
 	ROLE_ADMIN = 'ROLE_ADMIN',
	ROLE_SUPER_USER = 'ROLE_SUPER_USER',
	ROLE_USER = 'ROLE_USER',

	ROL_ADMIN = 'ROL_00000000',
	ROL_SAAS = 'ROL_00000001',
	ROL_PLAYER = 'ROL_00000003',
	// ROLE_SUPER_USER = 'ROLE_SUPER_USER',
	// ROLE_USER = 'ROLE_USER',
};

